stages:
  - build


build-job:
  stage: build
  script:
    - ant all
  artifacts:
    paths:
      - /home/dosi/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/dist/Tetris.jar
    expire_in: 1 week
