# GitLab CI/CD pipeline configuration

stages:
  - build
  - test
  - package

# Define the Docker build job
build-job:
  stage: build
  tags:
    - slave
  script:
    # Build the Docker image
    - docker build -t tetris-build .
    # Verify the build
    - docker images tetris-build

# Run tests inside the Docker container
test-job:
  stage: test
  tags:
    - slave
  script:
    # Run the container and execute Ant commands for testing
    - docker run --rm tetris-build ant compile-test
  needs:
    - build-job

# Package the application (JAR file)
package-job:
  stage: package
  tags:
    - slave
  script:
    # Run the container and execute the dist target
    - docker run --rm -v $(pwd)/dist:/app/dist tetris-build ant dist
  needs:
    - test-job
  artifacts:
    paths:
      - dist/Tetris.jar
    expire_in: 1 week

