stages:
  - retrieve
  - compile
  - dist
  - test


retrieve-job:
  stage: retrieve
  script:
    - ant retrieve



compile-job:
  stage: compile
  script:
    - ant compile
  artifacts:
    paths:
      - /home/dosi/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/bin
      - /home/dosi/Downloads/TetrisAnt/dist/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/bin
      - /home/dosi/Downloads/TetrisAnt/bin
    expire_in: 1 week


test-job:
  stage: retrieve
  script:
    - ant test
 

dist-job:
  stage: dist
  script:
    - ant dist
  artifacts:
    paths:
      - /home/dosi/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/dist
      - /home/dosi/Downloads/TetrisAnt/dist/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/dist
      - /home/dosi/Downloads/TetrisAnt/dist
    expire_in: 1 week

