stages:
  - retrieve
  - compile
  - dist


retrieve-job:
  stage: retrieve
  script:
    - ant retrieve
  needs:
    - clean-job

compile-job:
  stage: compile
  script:
    - ant compile
  needs:
    - retrieve-job

dist-job:
  stage: dist
  script:
    - ant dist
  artifacts:
    paths:
      - /home/dosi/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/dist/Tetris.jar
    expire_in: 1 week
