stages:
  - dist
  - test-reports
  - javadoc

dist-job:
  stage: dist
  script:
    - ant dist
  artifacts:
    paths:
      - /home/dosi/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/dist/Tetris.jar
    expire_in: 1 week


# Job pour générer les rapports de tests à partir des résultats JUnit
test-reports-job:
  stage: test-reports
  script:
    - ant test-reports


# Job pour générer la documentation Javadoc
javadoc-job:
  stage: javadoc
  script:
    - ant javadoc


