# Définition des stages pour le pipeline
stages:
  - compile
  - test
  - reports
  - javadoc

# Job pour la compilation du projet
compile-job:
  stage: compile
  script:
    - ant dist
  artifacts:
    paths:
      - dist/Tetris.jar
    expire_in: 1 week

# Job pour exécuter les tests unitaires et générer un rapport JUnit
test-job:
  stage: test
  script:
    - ant test
  artifacts:
    when: always
    paths:
      - bin/test-results
    reports:
      junit: bin/test-results/TEST-*.xml
    expire_in: 1 week
  allow_failure: false # Le pipeline échoue si les tests échouent

# Job pour générer les rapports de tests à partir des résultats JUnit
reports-job:
  stage: reports
  script:
    - ant test-reports
  artifacts:
    paths:
      - test-reports
    expire_in: 1 week

# Job pour générer la documentation Javadoc
javadoc-job:
  stage: javadoc
  script:
    - ant javadoc
  artifacts:
    paths:
      - javadoc
    expire_in: 1 week

# Job pour nettoyer le répertoire après chaque exécution de pipeline
cleanup-job:
  stage: cleanup
  script:
    - ant clean
