stages:
  - tag
  - clean
  - retrieve
  - compile
  - compile-test
  - javadoc
  - dist
  - test


tag-job:
  stage: tag
  tags:
    - slave
  script:
    - echo "Running on the slave runner"




clean-job:
  stage: clean
  tags:
    - slave
  script:
    - ant clean
  needs:
    - tag-job



retrieve-job:
  stage: retrieve
  tags:
    - slave
  script:
    - ant retrieve
  needs:
    - clean-job




compile-job:
  stage: compile
  tags:
    - slave
  script:
    - ant compile
  needs:
    - retrieve-job
  artifacts:
    paths:
      - bin/
    expire_in: 1 week

# Job pour compiler les tests unitaires
compile-test-job:
  stage: compile-test
  tags:
    - slave
  script:
    - ant compile-test
  needs:
    - compile-job
  artifacts:
    paths:
      - bin/test/
    expire_in: 1 week





javadoc-job:
  stage: javadoc
  tags:
    - slave
  script:
    - ant javadoc
  needs:
    - compile-job
  artifacts:
    paths:
      - javadoc/
    expire_in: 1 week

dist-job:
  stage: dist
  tags:
    - slave
  script:
    - ant dist
  needs:
    - javadoc-job
  artifacts:
    paths:
      - dist/Tetris.jar
    expire_in: 1 week