stages:
  - build


build-job:
  stage: build
  script:
    - ant all
  artifacts:
    paths:
      - Downloads/TetrisAnt/dist/builds/8sy1vFyDz/0/dosi/pic/dakhouch_hicham/tp_ci_cd/dist
    expire_in: 1 week
